### ISSUE TITLE
A mysterious bug

### ISSUE THREAD

**Issue by Mihailoff** [stevepraski/base-box-cookbook#10]
Somewhere here https://github.com/stevepraski/base-box-cookbook/blob/master/attributes/default.rb

**Comment by stevepraski** [comment]
Indeed.  The logic for setting 'permit_password_auth' is bad.

**Comment by stevepraski** [comment]
Fixed by removing logic: https://github.com/stevepraski/base-box-cookbook/commit/2719fd38167c6d77b6d5233dcc5c56a2f05614ca#diff-25e5d4a4446ae12a0d6f1162b6160375
